import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GoInvo Vercel Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://goinvo.com/vision/"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Vision <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Our view on the future of healthcare.
            </p>
          </a>

          <a
            href="https://goinvo.com/work/"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Work <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              See the health design projects we have worked on.
            </p>
          </a>

          <a
            href="https://goinvo.com/about/"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              About <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              See the team at GoInvo.
            </p>
          </a>

          <a
            href="https://goinvo.com/contact/"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Contact <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Tell us about your project.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
